### POST /api/v1/auth/signup

POST http://localhost:9595/api/v1/auth/signup
Content-Type: application/json

{
  "email": "muhammadhefzey@gmail.com",
  "username": "Muhammad Hefzey",
  "password": "password",
  "role": "INSTRUCTOR"
}


### POST /api/v1/auth/login

POST http://localhost:9595/api/v1/auth/login
Content-Type: application/json

{
  "email": "muhammadhefzey@gmail.com",
  "password": "password"
}


### POST /api/v1/auth/resend-confirmation-email

POST http://localhost:9595/api/v1/auth/resend-confirmation-email
Content-Type: application/json

{
  "email": "muhammadhefzey@gmail.com"
}
