### authorize

GET http://localhost:9595/api/v1/auth HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM2YWY2NzhiLWFjZmEtNDEzNS1iZmNjLTc0NjU3NWU2OGU2OSIsImlhdCI6MTc3MDI2Njk3MiwiZXhwIjoxNzcwMzUzMzcyfQ.8SDxZunSPRAsHsz46TNBIPqLVt_4obQdVjJ1mp_QdAY; Path=/; HttpOnly; SameSite=Lax


### signup

POST http://localhost:9595/api/v1/auth/signup HTTP/1.1
Content-Type: application/json

{
  "email": "student2@gmail.com",
  "password": "password",
  "role": "student",
  "username": "Muhammad Hefzey"
}


### login

POST http://localhost:9595/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "student@gmail.com",
  "password": "password"
}


### logout

GET http://localhost:9595/api/v1/auth/logout HTTP/1.1


### resend-confirmation-email

POST http://localhost:9595/api/v1/auth/resend-confirmation-email HTTP/1.1
Content-Type: application/json

{
  "email": "muhammadhefzey@gmail.com"
}


### forgot-password

POST http://localhost:9595/api/v1/auth/forgot-password HTTP/1.1
Content-Type: application/json

{
  "email": "muhammadhefzey@gmail.com"
}


### verify-otp

POST http://localhost:9595/api/v1/auth/verify-otp HTTP/1.1
Content-Type: application/json

{
  "email": "muhammadhefzey@gmail.com",
  "otp": "709046"
}


### reset-password

PATCH http://localhost:9595/api/v1/auth/reset-password HTTP/1.1
Content-Type: application/json

{
  "email": "muhammadhefzey@gmail.com",
  "newPassword": "newPassword",
  "otp": "709046"
}


### ################################################################################################


### update-user

PATCH http://localhost:9595/api/v1/user HTTP/1.1
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjMzQwMDQ0LWFlMTEtNDE1NC1hNTZjLWQ4YzkyNTljNTc5NyIsImlhdCI6MTc3MDIzNzAwNiwiZXhwIjoxNzcwMzIzNDA2fQ.cMobTLAejqxXxktB0M_ZuY8lI59DGMYUPuGGnXsL0sY; Path=/; HttpOnly; SameSite=Lax

{
  "password": "password",
  "username": "Muhammad Hefzey"
}


### delete-user

DELETE http://localhost:9595/api/v1/user HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjMzQwMDQ0LWFlMTEtNDE1NC1hNTZjLWQ4YzkyNTljNTc5NyIsImlhdCI6MTc3MDI2NjA3MSwiZXhwIjoxNzcwMzUyNDcxfQ.4U1qxMgYSjwATYMmTmyIqpVzgARYjbofYL5ToyD1Y6I; Path=/; HttpOnly; SameSite=Lax


### get-user-tracks

GET http://localhost:9595/api/v1/user/tracks HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzNjVkMjIwLWJjYzgtNDQzZS04OGE2LThkZWE0MWUwMTgxNCIsImlhdCI6MTc3MTE4NDQ1NiwiZXhwIjoxNzcxMjcwODU2fQ.nKWZTl1WxS9VXZBCX2Y1MI0S9DEXNmWDyJc7gh0tlXQ; Path=/; HttpOnly; SameSite=Lax


### select-track

PATCH http://localhost:9595/api/v1/user/select-track HTTP/1.1
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzNjVkMjIwLWJjYzgtNDQzZS04OGE2LThkZWE0MWUwMTgxNCIsImlhdCI6MTc3MDI5ODQxMSwiZXhwIjoxNzcwMzg0ODExfQ.B8P3ScxCx6GvTUFl02fBUfGKXtK4CWSLh55vyHIEwbU; Path=/; HttpOnly; SameSite=Lax

{
  "trackId": "3a6ab996-5845-4052-8518-664e2b1e30f1"
}


### quit-track

PATCH http://localhost:9595/api/v1/user/quit-track HTTP/1.1
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzNjVkMjIwLWJjYzgtNDQzZS04OGE2LThkZWE0MWUwMTgxNCIsImlhdCI6MTc3MDI2NjEwMSwiZXhwIjoxNzcwMzUyNTAxfQ.ZBlDkk1kQ98BllgqwICXW7nD-b_XDZas72E48drk4x0; Path=/; HttpOnly; SameSite=Lax

{
  "trackId": "f20f2083-9fe2-4e22-85d5-b67efbdbb946"
}


### get-user-courses

GET http://localhost:9595/api/v1/user/courses HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzNjVkMjIwLWJjYzgtNDQzZS04OGE2LThkZWE0MWUwMTgxNCIsImlhdCI6MTc3MTE4NDQ1NiwiZXhwIjoxNzcxMjcwODU2fQ.nKWZTl1WxS9VXZBCX2Y1MI0S9DEXNmWDyJc7gh0tlXQ; Path=/; HttpOnly; SameSite=Lax


### join-course

PATCH http://localhost:9595/api/v1/user/join-course HTTP/1.1
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzNjVkMjIwLWJjYzgtNDQzZS04OGE2LThkZWE0MWUwMTgxNCIsImlhdCI6MTc3MTE4NDQ1NiwiZXhwIjoxNzcxMjcwODU2fQ.nKWZTl1WxS9VXZBCX2Y1MI0S9DEXNmWDyJc7gh0tlXQ; Path=/; HttpOnly; SameSite=Lax

{
  "courseId": "7177df58-2a7b-4166-8896-c07b9d3ab866"
}


### quit-course

PATCH http://localhost:9595/api/v1/user/quit-course HTTP/1.1
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzNjVkMjIwLWJjYzgtNDQzZS04OGE2LThkZWE0MWUwMTgxNCIsImlhdCI6MTc3MDI2NjEwMSwiZXhwIjoxNzcwMzUyNTAxfQ.ZBlDkk1kQ98BllgqwICXW7nD-b_XDZas72E48drk4x0; Path=/; HttpOnly; SameSite=Lax

{
  "courseId": "27e2bffc-4662-49cc-955a-560f48b87aeb"
}


### get-user-staff-requests

GET http://localhost:9595/api/v1/user/staff-requests HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzNjVkMjIwLWJjYzgtNDQzZS04OGE2LThkZWE0MWUwMTgxNCIsImlhdCI6MTc3MDI2NjEwMSwiZXhwIjoxNzcwMzUyNTAxfQ.ZBlDkk1kQ98BllgqwICXW7nD-b_XDZas72E48drk4x0; Path=/; HttpOnly; SameSite=Lax


### get-user-student-requests

GET http://localhost:9595/api/v1/user/student-requests?status=approved HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzNjVkMjIwLWJjYzgtNDQzZS04OGE2LThkZWE0MWUwMTgxNCIsImlhdCI6MTc3MTM5MTQ0MSwiZXhwIjoxNzcxNDc3ODQxfQ._gPYQUs2HQAWjJuQlMa13xyJL5xtP4dkKQq846SGgVY; Path=/; HttpOnly; SameSite=Lax


### ################################################################################################


### get-tracks

GET http://localhost:9595/api/v1/tracks HTTP/1.1


### get-track

GET http://localhost:9595/api/v1/tracks/f20f2083-9fe2-4e22-85d5-b67efbdbb946 HTTP/1.1


### get-track-staff

GET http://localhost:9595/api/v1/tracks/d080583d-1fc8-4e80-9c2f-74f149f93e87/staff HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE1M2EwYzhiLWNhZjYtNDJjMy1hNTdkLTQ5NDcxODE3MDkzNCIsImlhdCI6MTc3MDE4MjU5MywiZXhwIjoxNzcwMjY4OTkzfQ.-lQHNpLXFN0wP9gGAJgnCTNFFvvcL64raspsLGhOshk; Path=/; HttpOnly; SameSite=Lax


### create-track

POST http://localhost:9595/api/v1/tracks HTTP/1.1
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM2YWY2NzhiLWFjZmEtNDEzNS1iZmNjLTc0NjU3NWU2OGU2OSIsImlhdCI6MTc3MDIzNDkwMSwiZXhwIjoxNzcwMzIxMzAxfQ.vZ7Rk5TWBl1Zpw35wx6gB9_inflWygqxh-2rd-0ooBs; Path=/; HttpOnly; SameSite=Lax

{
  "description": "a test track 2",
  "name": "track 2"
}


### update-track

PATCH http://localhost:9595/api/v1/tracks/5eb15a8f-e1d0-40c1-9603-c6a3a72fb366 HTTP/1.1
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE1M2EwYzhiLWNhZjYtNDJjMy1hNTdkLTQ5NDcxODE3MDkzNCIsImlhdCI6MTc3MDE4MjU5MywiZXhwIjoxNzcwMjY4OTkzfQ.-lQHNpLXFN0wP9gGAJgnCTNFFvvcL64raspsLGhOshk; Path=/; HttpOnly; SameSite=Lax

{
  "description": "Math 101 - Updated",
  "name": "Math 101"
}


### delete-track

DELETE http://localhost:9595/api/v1/tracks/5eb15a8f-e1d0-40c1-9603-c6a3a72fb366 HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE1M2EwYzhiLWNhZjYtNDJjMy1hNTdkLTQ5NDcxODE3MDkzNCIsImlhdCI6MTc3MDE4MjU5MywiZXhwIjoxNzcwMjY4OTkzfQ.-lQHNpLXFN0wP9gGAJgnCTNFFvvcL64raspsLGhOshk; Path=/; HttpOnly; SameSite=Lax


### ################################################################################################


### get-courses

GET http://localhost:9595/api/v1/courses?track=f20f2083-9fe2-4e22-85d5-b67efbdbb946 HTTP/1.1


### get-course

GET http://localhost:9595/api/v1/courses/fb108099-66c7-4baf-a035-4eb54b42e962 HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFkNzBiNzU5LTBiZjktNDdlMy1iYWNjLWMxOTk2NTA1NDg1NyIsImlhdCI6MTc3MTE4NTM4MywiZXhwIjoxNzcxMjcxNzgzfQ.DMV3r8sQTHLjdLgFuOQXsAeGc_KS-uNfR6lq5t0jXQw; Path=/; HttpOnly; SameSite=Lax


### create-course

POST http://localhost:9595/api/v1/courses HTTP/1.1
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM2YWY2NzhiLWFjZmEtNDEzNS1iZmNjLTc0NjU3NWU2OGU2OSIsImlhdCI6MTc3MDI2Njk3MiwiZXhwIjoxNzcwMzUzMzcyfQ.8SDxZunSPRAsHsz46TNBIPqLVt_4obQdVjJ1mp_QdAY; Path=/; HttpOnly; SameSite=Lax

{
  "assistantIds": [],
  "description": "a test course",
  "instructorIds": [],
  "name": "test course 5",
  "trackId": "f20f2083-9fe2-4e22-85d5-b67efbdbb946"
}


### update-course

PATCH http://localhost:9595/api/v1/courses/0ca32d70-81f9-46a1-ac07-d823a568251e HTTP/1.1
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE1M2EwYzhiLWNhZjYtNDJjMy1hNTdkLTQ5NDcxODE3MDkzNCIsImlhdCI6MTc3MDE4MjU5MywiZXhwIjoxNzcwMjY4OTkzfQ.-lQHNpLXFN0wP9gGAJgnCTNFFvvcL64raspsLGhOshk; Path=/; HttpOnly; SameSite=Lax

{
  "description": "Math 101 - Updated",
  "name": "Math 101"
}


### update-course-staff

PUT http://localhost:9595/api/v1/courses/46ffb1c8-395a-4895-a7e7-f07c9903c09d/staff HTTP/1.1
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM2YWY2NzhiLWFjZmEtNDEzNS1iZmNjLTc0NjU3NWU2OGU2OSIsImlhdCI6MTc3MDI2Njk3MiwiZXhwIjoxNzcwMzUzMzcyfQ.8SDxZunSPRAsHsz46TNBIPqLVt_4obQdVjJ1mp_QdAY; Path=/; HttpOnly; SameSite=Lax

{
  "assistantIds": [
    "0cbd8dbb-dc50-4658-8862-8391416fff01"
  ],
  "instructorIds": [
    "757d4cbb-eed8-4eee-809b-336b97f53dce"
  ],
  "trackId": "d080583d-1fc8-4e80-9c2f-74f149f93e87"
}


### delete-course

DELETE http://localhost:9595/api/v1/courses/246810c2-0361-4f16-bddb-f6c49568dbdf HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE1M2EwYzhiLWNhZjYtNDJjMy1hNTdkLTQ5NDcxODE3MDkzNCIsImlhdCI6MTc3MDE4MjU5MywiZXhwIjoxNzcwMjY4OTkzfQ.-lQHNpLXFN0wP9gGAJgnCTNFFvvcL64raspsLGhOshk; Path=/; HttpOnly; SameSite=Lax


### ################################################################################################


### get-posts

GET http://localhost:9595/api/v1/courses/dcc2096b-82a9-413d-a871-7bbd18e7de33/posts HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE1M2EwYzhiLWNhZjYtNDJjMy1hNTdkLTQ5NDcxODE3MDkzNCIsImlhdCI6MTc3MDE4MjU5MywiZXhwIjoxNzcwMjY4OTkzfQ.-lQHNpLXFN0wP9gGAJgnCTNFFvvcL64raspsLGhOshk; Path=/; HttpOnly; SameSite=Lax


### get-post

GET http://localhost:9595/api/v1/courses/27e2bffc-4662-49cc-955a-560f48b87aeb/posts/4458663e-2654-40c1-98fd-a1ac22057486 HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE1M2EwYzhiLWNhZjYtNDJjMy1hNTdkLTQ5NDcxODE3MDkzNCIsImlhdCI6MTc3MDE4MjU5MywiZXhwIjoxNzcwMjY4OTkzfQ.-lQHNpLXFN0wP9gGAJgnCTNFFvvcL64raspsLGhOshk; Path=/; HttpOnly; SameSite=Lax


### create-post

POST http://localhost:9595/api/v1/courses/dcc2096b-82a9-413d-a871-7bbd18e7de33/posts HTTP/1.1
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE1M2EwYzhiLWNhZjYtNDJjMy1hNTdkLTQ5NDcxODE3MDkzNCIsImlhdCI6MTc3MDE4MjU5MywiZXhwIjoxNzcwMjY4OTkzfQ.-lQHNpLXFN0wP9gGAJgnCTNFFvvcL64raspsLGhOshk; Path=/; HttpOnly; SameSite=Lax

{
  "content": "post content",
  "title": "post title"
}


### update-post

PATCH http://localhost:9595/api/v1/courses/dcc2096b-82a9-413d-a871-7bbd18e7de33/posts/e11be5f9-7be0-48ab-812b-de578f77390d HTTP/1.1
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE1M2EwYzhiLWNhZjYtNDJjMy1hNTdkLTQ5NDcxODE3MDkzNCIsImlhdCI6MTc3MDE4MjU5MywiZXhwIjoxNzcwMjY4OTkzfQ.-lQHNpLXFN0wP9gGAJgnCTNFFvvcL64raspsLGhOshk; Path=/; HttpOnly; SameSite=Lax

{
  "content": "new post content",
  "title": "new post title"
}


### delete-post

DELETE http://localhost:9595/api/v1/courses/dcc2096b-82a9-413d-a871-7bbd18e7de33/posts/e11be5f9-7be0-48ab-812b-de578f77390d HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE1M2EwYzhiLWNhZjYtNDJjMy1hNTdkLTQ5NDcxODE3MDkzNCIsImlhdCI6MTc3MDE4MjU5MywiZXhwIjoxNzcwMjY4OTkzfQ.-lQHNpLXFN0wP9gGAJgnCTNFFvvcL64raspsLGhOshk; Path=/; HttpOnly; SameSite=Lax


### ################################################################################################


### get-resources

GET http://localhost:9595/api/v1/courses/1/resources HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE1M2EwYzhiLWNhZjYtNDJjMy1hNTdkLTQ5NDcxODE3MDkzNCIsImlhdCI6MTc3MDE4MjU5MywiZXhwIjoxNzcwMjY4OTkzfQ.-lQHNpLXFN0wP9gGAJgnCTNFFvvcL64raspsLGhOshk; Path=/; HttpOnly; SameSite=Lax


### get-resource

GET http://localhost:9595/api/v1/courses/1/resources/1 HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE1M2EwYzhiLWNhZjYtNDJjMy1hNTdkLTQ5NDcxODE3MDkzNCIsImlhdCI6MTc3MDE4MjU5MywiZXhwIjoxNzcwMjY4OTkzfQ.-lQHNpLXFN0wP9gGAJgnCTNFFvvcL64raspsLGhOshk; Path=/; HttpOnly; SameSite=Lax


### delete-resource

DELETE http://localhost:9595/api/v1/courses/1/resources/1/delete HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE1M2EwYzhiLWNhZjYtNDJjMy1hNTdkLTQ5NDcxODE3MDkzNCIsImlhdCI6MTc3MDE4MjU5MywiZXhwIjoxNzcwMjY4OTkzfQ.-lQHNpLXFN0wP9gGAJgnCTNFFvvcL64raspsLGhOshk; Path=/; HttpOnly; SameSite=Lax


### ################################################################################################


### get-requests

GET http://localhost:9595/api/v1/requests HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE1M2EwYzhiLWNhZjYtNDJjMy1hNTdkLTQ5NDcxODE3MDkzNCIsImlhdCI6MTc3MDE4MjU5MywiZXhwIjoxNzcwMjY4OTkzfQ.-lQHNpLXFN0wP9gGAJgnCTNFFvvcL64raspsLGhOshk; Path=/; HttpOnly; SameSite=Lax


### get-request

GET http://localhost:9595/api/v1/requests/fab0a9e9-38e3-461c-bd51-2a9b5ec36ad5 HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE1M2EwYzhiLWNhZjYtNDJjMy1hNTdkLTQ5NDcxODE3MDkzNCIsImlhdCI6MTc3MDE4MjU5MywiZXhwIjoxNzcwMjY4OTkzfQ.-lQHNpLXFN0wP9gGAJgnCTNFFvvcL64raspsLGhOshk; Path=/; HttpOnly; SameSite=Lax


### create-request

POST http://localhost:9595/api/v1/requests HTTP/1.1
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM1ZGZiYzY2LTg4ZDQtNDU3OC1iMDJhLTI5MDE2M2EwMzU5OCIsImlhdCI6MTc3MDIxODQ4NSwiZXhwIjoxNzcwMzA0ODg1fQ.j2wwnZy2_k1pjgmIeIv_3-qnudySC9q1FfSeare4Ph8; Path=/; HttpOnly; SameSite=Lax

{
  "courseId": "fb108099-66c7-4baf-a035-4eb54b42e962",
  "message": "I would like to join this course."
}


### udate-request

PATCH http://localhost:9595/api/v1/requests/7ae9b3cd-cbfd-4360-92c6-62c0550ad885 HTTP/1.1
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUxNWZkMWY3LWY5MjQtNGY4OC1hNjAyLTIzYWM1ZWEzZWFkNSIsImlhdCI6MTc3MDIwNjI0NSwiZXhwIjoxNzcwMjkyNjQ1fQ.JpE8EHoA6dMDoc0eLL-AYgR4KXwDYmGf2JeO2o9zJfg; Path=/; HttpOnly; SameSite=Lax

{
  "message": "I would like to join this course because I am very interested in its content."
}


### answer-request

PATCH http://localhost:9595/api/v1/requests/fab0a9e9-38e3-461c-bd51-2a9b5ec36ad5/answer HTTP/1.1
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE1M2EwYzhiLWNhZjYtNDJjMy1hNTdkLTQ5NDcxODE3MDkzNCIsImlhdCI6MTc3MDE4MjU5MywiZXhwIjoxNzcwMjY4OTkzfQ.-lQHNpLXFN0wP9gGAJgnCTNFFvvcL64raspsLGhOshk; Path=/; HttpOnly; SameSite=Lax

{
  "status": "APPROVED"
}


### delete-request

DELETE http://localhost:9595/api/v1/requests/fab0a9e9-38e3-461c-bd51-2a9b5ec36ad5 HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM1ZGZiYzY2LTg4ZDQtNDU3OC1iMDJhLTI5MDE2M2EwMzU5OCIsImlhdCI6MTc3MDIxODQ4NSwiZXhwIjoxNzcwMzA0ODg1fQ.j2wwnZy2_k1pjgmIeIv_3-qnudySC9q1FfSeare4Ph8; Path=/; HttpOnly; SameSite=Lax


### ################################################################################################


### get-student-requests

GET http://localhost:9595/api/v1/student-requests?courseId=fb108099-66c7-4baf-a035-4eb54b42e962 HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUxNWZkMWY3LWY5MjQtNGY4OC1hNjAyLTIzYWM1ZWEzZWFkNSIsImlhdCI6MTc3MTM4OTYwNiwiZXhwIjoxNzcxNDc2MDA2fQ.MH1bkt-nGKqRpc1vJe7sc3zkd25F5sQlHRiXQNk9O5c; Path=/; HttpOnly; SameSite=Lax


### get-student-request

GET http://localhost:9595/api/v1/student-requests/85186b96-ea01-4f42-a743-25a21d8c9e26 HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUxNWZkMWY3LWY5MjQtNGY4OC1hNjAyLTIzYWM1ZWEzZWFkNSIsImlhdCI6MTc3MTM4OTYwNiwiZXhwIjoxNzcxNDc2MDA2fQ.MH1bkt-nGKqRpc1vJe7sc3zkd25F5sQlHRiXQNk9O5c; Path=/; HttpOnly; SameSite=Lax


### create-student-request

POST http://localhost:9595/api/v1/student-requests HTTP/1.1
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzNjVkMjIwLWJjYzgtNDQzZS04OGE2LThkZWE0MWUwMTgxNCIsImlhdCI6MTc3MTE4NDQ1NiwiZXhwIjoxNzcxMjcwODU2fQ.nKWZTl1WxS9VXZBCX2Y1MI0S9DEXNmWDyJc7gh0tlXQ; Path=/; HttpOnly; SameSite=Lax

{ 
  "courseId": "fb108099-66c7-4baf-a035-4eb54b42e962"
}


### answer-student-request

PATCH http://localhost:9595/api/v1/student-requests/85186b96-ea01-4f42-a743-25a21d8c9e26/answer HTTP/1.1
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUxNWZkMWY3LWY5MjQtNGY4OC1hNjAyLTIzYWM1ZWEzZWFkNSIsImlhdCI6MTc3MTM4OTYwNiwiZXhwIjoxNzcxNDc2MDA2fQ.MH1bkt-nGKqRpc1vJe7sc3zkd25F5sQlHRiXQNk9O5c; Path=/; HttpOnly; SameSite=Lax

{ 
  "status": "APPROVED"
}


### delete-student-request

DELETE http://localhost:9595/api/v1/student-requests/85186b96-ea01-4f42-a743-25a21d8c9e26 HTTP/1.1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzNjVkMjIwLWJjYzgtNDQzZS04OGE2LThkZWE0MWUwMTgxNCIsImlhdCI6MTc3MTM5MTQ0MSwiZXhwIjoxNzcxNDc3ODQxfQ._gPYQUs2HQAWjJuQlMa13xyJL5xtP4dkKQq846SGgVY; Path=/; HttpOnly; SameSite=Lax
