### signup

POST http://localhost:9595/api/v1/auth/signup
Content-Type: application/json

{
  "email": "muhammadhefzey@gmail.com",
  "username": "Muhammad Hefzey",
  "password": "password",
  "role": "INSTRUCTOR"
}


### login

POST http://localhost:9595/api/v1/auth/login
Content-Type: application/json

{
  "email": "muhammadhefzey@gmail.com",
  "password": "password"
}


### resend-confirmation-email

POST http://localhost:9595/api/v1/auth/resend-confirmation-email
Content-Type: application/json

{
  "email": "muhammadhefzey@gmail.com"
}


### forgot-password

POST http://localhost:9595/api/v1/auth/forgot-password
Content-Type: application/json

{
  "email": "muhammadhefzey@gmail.com"
}


### reset-password

PATCH http://localhost:9595/api/v1/auth/reset-password/cf3382eb9cd291ffb9def5b97cb905099de0921a2244358db141524c790bb065
Content-Type: application/json

{
  "email": "muhammadhefzey@gmail.com",
  "newPassword": "newPassword"
}


####################################################################################################


### get-subjects

GET http://localhost:9595/api/v1/subjects


### get-subject

GET http://localhost:9595/api/v1/subjects/1


### create-subject

POST http://localhost:9595/api/v1/subjects/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTc1OTY4MjczMiwiZXhwIjoxNzYyMjc0NzMyfQ.lVTW42rECQR4Jjg3qflvPiGmtnrGvDyBnkgfrGJxaRU

{
  "name": "CS 101"
}


### update-subject

PATCH http://localhost:9595/api/v1/subjects/1/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTc1OTY4MjczMiwiZXhwIjoxNzYyMjc0NzMyfQ.lVTW42rECQR4Jjg3qflvPiGmtnrGvDyBnkgfrGJxaRU

{
  "name": "Math 101",
  "description": "Math 101 - Updated"
}


### delete-subject

DELETE http://localhost:9595/api/v1/subjects/7/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTc1OTY4MjczMiwiZXhwIjoxNzYyMjc0NzMyfQ.lVTW42rECQR4Jjg3qflvPiGmtnrGvDyBnkgfrGJxaRU


####################################################################################################


### get-posts

GET http://localhost:9595/api/v1/subjects/1/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTc1OTY4MjczMiwiZXhwIjoxNzYyMjc0NzMyfQ.lVTW42rECQR4Jjg3qflvPiGmtnrGvDyBnkgfrGJxaRU


### get-post

GET http://localhost:9595/api/v1/subjects/1/posts/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTc1OTY4MjczMiwiZXhwIjoxNzYyMjc0NzMyfQ.lVTW42rECQR4Jjg3qflvPiGmtnrGvDyBnkgfrGJxaRU


### create-post

POST http://localhost:9595/api/v1/subjects/1/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTc1OTY4MjczMiwiZXhwIjoxNzYyMjc0NzMyfQ.lVTW42rECQR4Jjg3qflvPiGmtnrGvDyBnkgfrGJxaRU

{
  "title": "post title",
  "content": "post content"
}


### update-post

PATCH http://localhost:9595/api/v1/subjects/1/posts/1/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTc1OTY4MjczMiwiZXhwIjoxNzYyMjc0NzMyfQ.lVTW42rECQR4Jjg3qflvPiGmtnrGvDyBnkgfrGJxaRU

{
  "title": "new post title",
  "content": "new post content"
}


### delete-post

DELETE http://localhost:9595/api/v1/subjects/1/posts/4/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTc1OTY4MjczMiwiZXhwIjoxNzYyMjc0NzMyfQ.lVTW42rECQR4Jjg3qflvPiGmtnrGvDyBnkgfrGJxaRU
