### signup

POST http://localhost:9595/api/v1/auth/signup
Content-Type: application/json

{
  "email": "muhammadhefzey@gmail.com",
  "username": "Muhammad Hefzey",
  "password": "password",
  "role": "INSTRUCTOR"
}


### login

POST http://localhost:9595/api/v1/auth/login
Content-Type: application/json

{
  "email": "muhammadhefzey@gmail.com",
  "password": "password"
}


### logout

GET http://localhost:9595/api/v1/auth/logout


### authorize

GET http://localhost:9595/api/v1/auth/authorize


### resend-confirmation-email

POST http://localhost:9595/api/v1/auth/resend-confirmation-email
Content-Type: application/json

{
  "email": "muhammadhefzey@gmail.com"
}


### forgot-password

POST http://localhost:9595/api/v1/auth/forgot-password
Content-Type: application/json

{
  "email": "muhammadhefzey@gmail.com"
}


### verify-otp

POST http://localhost:9595/api/v1/auth/verify-otp
Content-Type: application/json

{
  "otp": "639330",
  "email": "muhammadhefzey@gmail.com"
}


### reset-password

PATCH http://localhost:9595/api/v1/auth/reset-password/639330
Content-Type: application/json

{
  "email": "muhammadhefzey@gmail.com",
  "newPassword": "newPassword"
}


####################################################################################################


### get-subjects

GET http://localhost:9595/api/v1/subjects


### get-subject

GET http://localhost:9595/api/v1/subjects/1


### create-subject

POST http://localhost:9595/api/v1/subjects/create
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTc2MDM2MTExNSwiZXhwIjoxNzYyOTUzMTE1fQ.su1VdvZjY-5vUDCS5rF3mKYGgixAR572nsm9VSJ9x_s; Path=/; HttpOnly

{
  "name": "CS 101"
}


### update-subject

PATCH http://localhost:9595/api/v1/subjects/1/update
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTc2MDM2MTExNSwiZXhwIjoxNzYyOTUzMTE1fQ.su1VdvZjY-5vUDCS5rF3mKYGgixAR572nsm9VSJ9x_s; Path=/; HttpOnly

{
  "name": "Math 101",
  "description": "Math 101 - Updated"
}


### delete-subject

DELETE http://localhost:9595/api/v1/subjects/7/delete
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTc2MDM2MTExNSwiZXhwIjoxNzYyOTUzMTE1fQ.su1VdvZjY-5vUDCS5rF3mKYGgixAR572nsm9VSJ9x_s; Path=/; HttpOnly


####################################################################################################


### get-posts

GET http://localhost:9595/api/v1/subjects/1/posts
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTc2MDM2MTExNSwiZXhwIjoxNzYyOTUzMTE1fQ.su1VdvZjY-5vUDCS5rF3mKYGgixAR572nsm9VSJ9x_s; Path=/; HttpOnly


### get-post

GET http://localhost:9595/api/v1/subjects/1/posts/1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTc2MDM2MTExNSwiZXhwIjoxNzYyOTUzMTE1fQ.su1VdvZjY-5vUDCS5rF3mKYGgixAR572nsm9VSJ9x_s; Path=/; HttpOnly


### create-post

POST http://localhost:9595/api/v1/subjects/1/posts/create
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTc2MDM2MTExNSwiZXhwIjoxNzYyOTUzMTE1fQ.su1VdvZjY-5vUDCS5rF3mKYGgixAR572nsm9VSJ9x_s; Path=/; HttpOnly

{
  "title": "post title",
  "content": "post content"
}


### update-post

PATCH http://localhost:9595/api/v1/subjects/1/posts/1/update
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTc2MDM2MTExNSwiZXhwIjoxNzYyOTUzMTE1fQ.su1VdvZjY-5vUDCS5rF3mKYGgixAR572nsm9VSJ9x_s; Path=/; HttpOnly

{
  "title": "new post title",
  "content": "new post content"
}


### delete-post

DELETE http://localhost:9595/api/v1/subjects/1/posts/4/delete
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTc2MDM2MTExNSwiZXhwIjoxNzYyOTUzMTE1fQ.su1VdvZjY-5vUDCS5rF3mKYGgixAR572nsm9VSJ9x_s; Path=/; HttpOnly
